Adding several products
CraftAcademy/slowfood_api_august_2021 pull request #9
Opened 2021-10-06 15:03 UTC by Fraseer

PT Link: https://www.pivotaltracker.com/story/show/179716933

### User Story:
As a user
In order to order the food that I want
I would like to be able update my cart with more products

### Changes Proposed
- Create tests for updating the cart with a new product
- Implement a update method in the cart controller
- Update message response to include new item and http status

### What we learned working on this feature
Keep it in scope
Cart.find(params['id']) & current_user.carts dont work the same way
Setting the right premises in the before blocks for testing

### Packages / Gems added
N/A

### Screenshots (Videos)
![image](https://user-images.githubusercontent.com/26599559/136229561-309ba2ea-1994-40bd-8886-7d9fff10cc80.png)

2021-10-06 19:33 UTC, lukeperrin10 requested changes
Please remove the binding.pry otherwise looks good

2021-10-06 19:33 UTC, lukeperrin10 commented on spec/requests/api/api_adds_several_products_to_the_cart_spec.rb
> +      # binding.pry
This should be removed.

2021-10-06 19:38 UTC, Fraseer commented on spec/requests/api/api_adds_several_products_to_the_cart_spec.rb
> +      # binding.pry
I have pushed up the change

2021-10-06 19:43 UTC, lukeperrin10 approved these changes

2021-10-06 19:43 UTC, merged

2021-10-07 07:16 UTC, tochman commented on spec/requests/api/api_adds_several_products_to_the_cart_spec.rb
> +  let(:cart) { create(:cart, user_id: user.id) }
```
let(:cart) { create(:cart, user: user) }
```

2021-10-07 07:17 UTC, tochman commented on spec/requests/api/api_adds_several_products_to_the_cart_spec.rb
> +      cart.cart_products.create(product_id: product_existing.id)
```
cart.cart_products.create(product: product_existing)
```

2021-10-07 07:18 UTC, tochman commented on spec/requests/api/api_adds_several_products_to_the_cart_spec.rb
> +      put "/api/carts/#{cart.id}",
```
put carts_path(cart)
```